### ISSUE TITLE
Render-blocking resources table not sorted

### ISSUE THREAD

**Issue by jburger424** [googleads/publisher-ads-lighthouse-plugin#61]

**Comment by jonkeller** [comment]
Cannot reproduce:
1. Couldn't find a website that naturally failed this audit, so set MINIMUM_WASTED_MS to 0 instead of 50
2. Ran an audit on https://www.nba.com
3. Render-blocking resources table is sorted by start time.
Closing this bug. @jburger424 please re-open if you're wanting it sorted by some other column.
